export const CHARACTER_ATTRIBUTES = [
  'STRENGTH',
  'AGILITY',
  'VIGOR',
  'INTELLIGENCE',
  'AWARENESS',
  'CHARISMA',
] as const;

export const ATTRIBUTE_CREATION_POINTS = 6;
export const ATTRIBUTE_CREATION_CAP = 3;
export const ATTRIBUTE_MAX_LEVEL = 5;
